create table Covid_Data(
	DATE_OF_INTEREST DATE,
	MN_CASE_COUNT INT,
	MN_HOSPITALIZED_COUNT INT,
	MN_DEATH_COUNT INT,
	QN_CASE_COUNT INT,
	QN_HOSPITALIZED_COUNT INT,
	QN_DEATH_COUNT INT,
	BK_CASE_COUNT INT,
	BK_HOSPITALIZED_COUNT INT,
	BK_DEATH_COUNT	INT,
	BX_CASE_COUNT	INT,
	BX_HOSPITALIZED_COUNT	INT,
	BX_DEATH_COUNT	INT,
	SI_CASE_COUNT INT,
	SI_HOSPITALIZED_COUNT INT, 
	SI_DEATH_COUNT INT);
	
select * from covid_data;	


